on: [ workflow_call ]

jobs:
  mockserver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Start MockServer
        uses: addnab/docker-run-action@v3
        with:
          image: mockserver/mockserver:latest
          run: |
            curl -X 'PUT' \
              'http://localhost:1080/mockserver/openapi' \
              -H 'accept: application/json' \
              -H 'Content-Type: application/json' \
              -d '{
              "specUrlOrPayload": "https://raw.githubusercontent.com/f1betting/F1API/main/OpenAPI.json"
            }'
          
            curl -X 'GET' \
              'http://localhost:1080/event/next' \
              -H 'accept: application/json'
