on: [ workflow_call ]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # dependency's
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      # prism mockserver
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: |
          yarn global add @stoplight/prism-cli pm2
      # testing
      - name: Test with pytest
        run: |
          pm2 start "prism mock https://raw.githubusercontent.com/f1betting/F1API/main/OpenAPI.json --upstream-proxy ${{ secrets.F1_API }}" --name "PrismServer"
          coverage run --source=app --branch -m unittest discover -v
          pm2 stop PrismServer
        env:
          DB_URI: ${{ secrets.DB_URI }}
          DB_NAME: ${{ secrets.DB_NAME }}
          F1_API: ${{ secrets.F1_API }}
          GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
      - name: Testing rapport
        run: python -m coverage xml
      # display report
      - name: Get Coverage
        if: github.event_name == 'pull_request'
        uses: orgoro/coverage@v3
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.0
          thresholdNew: 0.0
          thresholdModified: 0 # looks at all modified lines not only the python files
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-testing-report
          path: ./coverage.xml
          retention-days: 14