on: [ workflow_call ]

jobs:
  mockserver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Start MockServer
        uses: addnab/docker-run-action@v3
        with:
          image: mockserver/mockserver:latest
          shell: bash
          run: |
            curl -X 'PUT' \
              'http://localhost:1080/mockserver/openapi' \
              -H 'accept: application/json' \
              -H 'Content-Type: application/json' \
              -d '{
              "specUrlOrPayload": "https://raw.githubusercontent.com/f1betting/F1API/main/OpenAPI.json"
            }'
          
            curl -X 'GET' \
              'http://127.0.0.1:8000/event/next' \
              -H 'accept: application/json'
